apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
#to use regex
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  #all the routing rules we want to apply for the ingress controller
  #k8s can have multiple domains in a single cluster hence you have to mention the host
    - host: posts.com
      http:
        paths:
        #paths are ordered in the most important order to the least
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-service-srv
                port:
                  number: 4002  
#nginx doesn't support dynamic routing with /:id so we have to use regex.                  
          - path: /posts/?(.*)/comments
            pathType: Prefix
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
            #for SPA, you have to add regex to match any path, this has to be last, if it is at the top it will always
            #go to the react app
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000  

#since the posts.com is changed in /etc/hosts (C:\windows\system32\drivers\etc\hosts) browser will not go to the posts.com 
#instead ingress-nginx will take the request and redirect it to the appropriate service
#based on the service given in backend by path and that service will redirect it to the pod                  